### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by holovantus** [Rdimo/Hazard-Token-Grabber-V2#11]
Traceback (most recent call last):
  File "main.py", line 1, in <module>
ImportError: DLL load failed while importing win32crypt: The specified module could not be found.

Any fixes? I've attempted to reinstall pywin32 multiple times yet it cannot find the module?

**Comment by holovantus** [comment]
I fixed my old issue but now another error has popped up


Traceback (most recent call last):
  File "main.py", line 303, in <module>
  File "main.py", line 22, in __init__
  File "main.py", line 239, in grabTokens
  File "json\__init__.py", line 339, in loads
TypeError: the JSON object must be str, bytes or bytearray, not HTTPResponse

**Comment by Rdimo** [comment]
to fix the win32crypt problem just do `pip install pypiwin32` and the bug should be fixed now (hopefully)
