### ISSUE TITLE
Isn't working

### ISSUE THREAD

**Issue by fluencies** [Rdimo/Hazard-Token-Grabber-V2#13]
Traceback (most recent call last):
  File "main.py", line 303, in <module>
  File "main.py", line 22, in __init__
  File "main.py", line 234, in grabTokens
  File "_strptime.py", line 568, in _strptime_datetime
  File "_strptime.py", line 352, in _strptime
ValueError: unconverted data remains: +00:00

get this msg when I open

**Comment by Rdimo** [comment]
ill look into it thank you

**Comment by Rdimo** [comment]
should be fixed by now
