### ISSUE TITLE
error

### ISSUE THREAD

**Issue by AzzOn72** [Rdimo/Hazard-Token-Grabber-V2#15]
Traceback (most recent call last):
  File "requests\packages\urllib3\util\ssl_.py", line 308, in ssl_wrap_socket
FileNotFoundError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 413, in send
  File "requests\packages\urllib3\connectionpool.py", line 591, in urlopen
  File "requests\packages\urllib3\connectionpool.py", line 350, in _make_request
  File "requests\packages\urllib3\connectionpool.py", line 835, in _validate_conn
  File "requests\packages\urllib3\connection.py", line 316, in connect
  File "requests\packages\urllib3\util\ssl_.py", line 310, in ssl_wrap_socket
requests.packages.urllib3.exceptions.SSLError: [Errno 2] No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "method.py", line 303, in <module>
  File "method.py", line 22, in __init__
  File "method.py", line 189, in grabTokens
  File "requests\api.py", line 70, in get
  File "requests\api.py", line 56, in request
  File "requests\sessions.py", line 488, in request
  File "requests\sessions.py", line 609, in send
  File "requests\adapters.py", line 497, in send
requests.exceptions.SSLError: [Errno 2] No such file or directory

**Comment by Rdimo** [comment]
you got some issues with your lib, try and see if [this](https://stackoverflow.com/questions/27726815/requests-exceptions-sslerror-errno-2-no-such-file-or-directory) helps
