### ISSUE TITLE
failed to exute script

### ISSUE THREAD

**Issue by Nadav43p** [Rdimo/Hazard-Token-Grabber-V2#160]
Traceback (most recent call last):
  File "main.py", line 459, in <module>
  File "main.py", line 65, in __init__
  File "main.py", line 407, in SendInfo
TypeError: 'NoneType' object is not subscriptableTraceback (most recent call last):
  File "main.py", line 459, in <module>
  File "main.py", line 65, in __init__
  File "main.py", line 407, in SendInfo
TypeError: 'NoneType' object is not subscriptable

**Comment by Nadav43p** [comment]
it shows like this when i run the exe

**Comment by Rdimo** [comment]
should be fixed hopefully
