### ISSUE TITLE
pls help me fix this issue

### ISSUE THREAD

**Issue by demonsdj** [Rdimo/Hazard-Token-Grabber-V2#161]
Traceback (most recent call last):
  File "main.py", line 458, in <module>
  File "main.py", line 64, in __init__
  File "main.py", line 406, in SendInfo
TypeError: 'NoneType' object is not subscriptable
it says this wen i try to run the exe file

**Comment by addi00000** [comment]
download new version, should be fixed

**Comment by Rdimo** [comment]
this is fixed now
