### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by chiron852** [Rdimo/Hazard-Token-Grabber-V2#172]
Traceback (most recent call last):
  File "main.py", line 412, in <module>
  File "main.py", line 46, in __init__
  File "main.py", line 286, in grabTokens
UnboundLocalError: local variable 'r' referenced before assignment

**Comment by Rdimo** [comment]
ty ill look into it rn

**Comment by Rdimo** [comment]
should be fixed now @chiron852

**Comment by chiron852** [comment]
yes its fixed

**Comment by Rdimo** [comment]
👍
