### ISSUE TITLE
winerror

### ISSUE THREAD

**Issue by DylieMan102** [Rdimo/Hazard-Token-Grabber-V2#193]
Traceback (most recent call last):
  File "main.py", line 527, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 641, in run_until_complete
  File "main.py", line 145, in init
PermissionError: [WinError 32] The process cannot access the file because it is being used by another process: 'C:\\Users\\(userhere)\\AppData\\Local\\Temp\\Hazard_Token_Grabber_V2\\Google Passwords.txt'

also the injector is not working. is not giving new password or token when changed.

**Comment by Rdimo** [comment]
ye hold on lmao, fixing alot of bugs rn, should be fixed in a min

**Comment by Rdimo** [comment]
alr, fixed this + other issues now

**Comment by Rdimo** [comment]
ty @DylieMan102 for telling
