### ISSUE TITLE
Dll Load Failed while importing win32crypt

### ISSUE THREAD

**Issue by RedBeanis** [Rdimo/Hazard-Token-Grabber-V2#242]
whenever I execute the .exe file, it gives me this error:

"Traceback (most recent call last):
  File "main.py", line 19, in <module>
ImportError: DLL load failed while importing win32crypt: The specified module could not be found."
![aaaa2](https://user-images.githubusercontent.com/104285325/166135049-3f6d71c2-63dc-4691-91e4-e18f0ef62c61.PNG)

**Comment by Maywitz** [comment]
whats your discord il help

**Comment by Rdimo** [comment]
> whenever I execute the .exe file, it gives me this error:
> 
> "Traceback (most recent call last): File "main.py", line 19, in ImportError: DLL load failed while importing win32crypt: The specified module could not be found." ![aaaa2](https://user-images.githubusercontent.com/104285325/166135049-3f6d71c2-63dc-4691-91e4-e18f0ef62c61.PNG)

ur pypiwin32 installed incorrectly, try just reinstall it, otherwise reinstall python and install pypiwin32 again
