### ISSUE TITLE
Cannot import name 'NoReturn'

### ISSUE THREAD

**Issue by vinbocheng** [Rdimo/Hazard-Token-Grabber-V2#253]
Traceback (most recent call last):
  File "main.py", line 3, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\__init__.py", line 2, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_api.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_client.py", line 9, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_auth.py", line 10, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_models.py", line 16, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_content.py", line 17, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_multipart.py", line 14, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "httpx\_utils.py", line 13, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sniffio\__init__.py", line 10, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "sniffio\_impl.py", line 1, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "contextvars\__init__.py", line 4, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "immutables\__init__.py", line 18, in <module>
  File "PyInstaller\loader\pyimod03_importers.py", line 495, in exec_module
  File "immutables\_protocols.py", line 6, in <module>
ImportError: cannot import name 'NoReturn'

**Comment by vinbocheng** [comment]
Using py 3.10.4

**Comment by Rdimo** [comment]
that's some error with your pyinstaller and not the grabber itself, try googling and see if you can find a solution
