### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PedaretKhor** [Rdimo/Hazard-Token-Grabber-V2#260]
C:\Users\User>python C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'str' object is not callable

Discord 1.0.9004
Quitting secondary instance.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 668, in <module>
    asyncio.run(Hazard_Token_Grabber_V2().init())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 181, in init
    self.finish()
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 495, in finish
    ip = data.get('ip').replace(" ", "")
AttributeError: 'NoneType' object has no attribute 'replace'

C:\Users\User>python C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py
Exception in thread Thread-8:
Traceback (most recent call last):
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
TypeError: 'str' object is not callable

Discord 1.0.9004
Quitting secondary instance.
Traceback (most recent call last):
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 668, in <module>
    asyncio.run(Hazard_Token_Grabber_V2().init())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 181, in init
    self.finish()
  File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 495, in finish
    ip = data.get('ip').replace(" ", "")
AttributeError: 'NoneType' object has no attribute 'replace'

This Error is for main.py file

**Comment by Maywitz** [comment]
you don't have ip

**Comment by Rdimo** [comment]
> C:\Users\User>python C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py Exception in thread Thread-8: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run self._target(*self._args, **self._kwargs) TypeError: 'str' object is not callable
> 
> Discord 1.0.9004 Quitting secondary instance. Traceback (most recent call last): File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 668, in asyncio.run(Hazard_Token_Grabber_V2().init()) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 181, in init self.finish() File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 495, in finish ip = data.get('ip').replace(" ", "") AttributeError: 'NoneType' object has no attribute 'replace'
> 
> C:\Users\User>python C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py Exception in thread Thread-8: Traceback (most recent call last): File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 1009, in _bootstrap_inner self.run() File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\threading.py", line 946, in run self._target(*self._args, **self._kwargs) TypeError: 'str' object is not callable
> 
> Discord 1.0.9004 Quitting secondary instance. Traceback (most recent call last): File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 668, in asyncio.run(Hazard_Token_Grabber_V2().init()) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run return loop.run_until_complete(main) File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete return future.result() File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 181, in init self.finish() File "C:\Users\User\Desktop\sp\logs\Hazard-Nuker-master\Hazard-Token-Grabber-V2-master\main.py", line 495, in finish ip = data.get('ip').replace(" ", "") AttributeError: 'NoneType' object has no attribute 'replace'
> 
> This Error is for main.py file

lmao dam

**Comment by Rdimo** [comment]
ill fix that rn dw

**Comment by Rdimo** [comment]
ight fixed this now, ty for reporting @PedaretKhor

**Comment by PedaretKhor** [comment]
C:\WINDOWS\system32>python "C:\Users\User\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py"
Traceback (most recent call last):
  File "C:\Users\User\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 669, in <module>
    asyncio.run(Hazard_Token_Grabber_V2().init())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\User\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 181, in init
    await self.injector()
  File "C:\Users\User\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 204, in injector
    if self.startup not in argv[0]:
TypeError: 'in <string>' requires string as left operand, not method

its not fixed but tnx

**Comment by PedaretKhor** [comment]
@Rdimo
