### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by PedaretKhor** [Rdimo/Hazard-Token-Grabber-V2#266]
PS C:\Users\Hirad> & C:/Users/Hirad/AppData/Local/Microsoft/WindowsApps/python3.10.exe "c:/Users/Hirad/Desktop/New folder (2)/Hazard-Token-Grabber-V2-master/main.py"
Traceback (most recent call last):
  File "c:\Users\Hirad\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 669, in <module>
    asyncio.run(Hazard_Token_Grabber_V2().init())
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.10_3.10.1264.0_x64__qbz5n2kfra8p0\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "c:\Users\Hirad\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 181, in init
    await self.injector()
  File "c:\Users\Hirad\Desktop\New folder (2)\Hazard-Token-Grabber-V2-master\main.py", line 204, in injector
    if self.startup not in argv[0]:
TypeError: 'in <string>' requires string as left operand, not method

**Comment by Rdimo** [comment]
ye fixed that in the new update, so just update it
