### ISSUE TITLE
??????

### ISSUE THREAD

**Issue by TeteuXD2** [Rdimo/Hazard-Token-Grabber-V2#297]
Traceback (most recent call last):
  File "main.py", line 670, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "main.py", line 182, in init
  File "main.py", line 495, in finish
ValueError: not enough values to unpack (expected 7, got 3)

What i do?

**Comment by Rdimo** [comment]
alr ty for reporting lemme fix rq

**Comment by Rdimo** [comment]
alr this is now fixed ty for telling @TeteuXD2
