### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by waleedhill** [Rdimo/Hazard-Token-Grabber-V2#371]
Traceback (most recent call last):
  File "main.py", line 684, in <module>
  File "asyncio\runners.py", line 44, in run
  File "asyncio\base_events.py", line 646, in run_until_complete
  File "main.py", line 188, in init
  File "main.py", line 493, in finish
  File "httpx\_models.py", line 743, in json
  File "json\__init__.py", line 346, in loads
  File "json\decoder.py", line 337, in decode
  File "json\decoder.py", line 355, in raw_decode
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by Rdimo** [comment]
ur using an old ass version, update it

**Comment by waleedhill** [comment]
old version of what? the script or python, if python then no because i have the most recent one
