### ISSUE TITLE
1.8.4 Errors

### ISSUE THREAD

**Issue by xsilas43** [Rdimo/Hazard-Token-Grabber-V2#401]
Traceback (most recent call last):
  File "C:\Users\xsilas43\Desktop\Files\Hazard-Token-Grabber-V2-master\main.py", line 89, in <module>
    class Functions(object):
  File "C:\Users\xsilas43\Desktop\Files\Hazard-Token-Grabber-V2-master\main.py", line 116, in Functions
    def create_temp_file(_dir: str | os.PathLike = gettempdir()):
TypeError: unsupported operand type(s) for |: 'type' and 'ABCMeta'

Stops script from executing.

**Comment by Rdimo** [comment]
this is fixed now
