### ISSUE TITLE
Error No 11004

### ISSUE THREAD

**Issue by MaybeFlyZ** [Rdimo/Hazard-Token-Grabber-V2#432]
I get this error when running the exe. 

Traceback (most recent call last):
  File "httpcore\_exceptions.py", line 8, in map_exceptions
  File "httpcore\backends\sync.py", line 82, in connect_tcp
  File "socket.py", line 824, in create_connection
  File "socket.py", line 955, in getaddrinfo
socket.gaierror: [Errno 11004] getaddrinfo failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "httpx\_transports\default.py", line 60, in map_httpcore_exceptions
  File "httpx\_transports\default.py", line 218, in handle_request
  File "httpcore\_sync\connection_pool.py", line 253, in handle_request
  File "httpcore\_sync\connection_pool.py", line 237, in handle_request
  File "httpcore\_sync\connection.py", line 86, in handle_request
  File "httpcore\_sync\connection.py", line 63, in handle_request
  File "httpcore\_sync\connection.py", line 111, in _connect
  File "httpcore\backends\sync.py", line 81, in connect_tcp
  File "contextlib.py", line 153, in __exit__
  File "httpcore\_exceptions.py", line 12, in map_exceptions
httpcore.ConnectError: [Errno 11004] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "main.py", line 794, in <module>
  File "main.py", line 168, in __init__
  File "main.py", line 143, in network_info
  File "httpx\_api.py", line 189, in get
  File "httpx\_api.py", line 100, in request
  File "httpx\_client.py", line 802, in request
  File "httpx\_client.py", line 889, in send
  File "httpx\_client.py", line 917, in _send_handling_auth
  File "httpx\_client.py", line 954, in _send_handling_redirects
  File "httpx\_client.py", line 990, in _send_single_request
  File "httpx\_transports\default.py", line 217, in handle_request
  File "contextlib.py", line 153, in __exit__
  File "httpx\_transports\default.py", line 77, in map_httpcore_exceptions
httpx.ConnectError: [Errno 11004] getaddrinfo failed

**Comment by Rdimo** [comment]
ye you got some sort of connection error but unless the internet cut while hazard v2 was running it should've exited if it can't establish a connection

**Comment by Rdimo** [comment]
and there is no function named `getaddrinfo` so this is something you added or ur using an older version

**Comment by MaybeFlyZ** [comment]
> and there is no function named `getaddrinfo` so this is something you added or ur using an older version

Its a fresh install and I didn't add anything to it.

**Comment by MaybeFlyZ** [comment]
> It couldn't get url address info aka connection error as it clearly says on the ouput. maybe try to connect to lan before executing?

I was on lan when I ran it.

**Comment by FuckingToasters** [comment]
> > It couldn't get url address info aka connection error as it clearly says on the ouput. maybe try to connect to lan before executing?
> 
> I was on lan when I ran it.

Ok but there is clearly something working with the connection. Maybe a firewall is blocking it etc.
