### ISSUE TITLE
Not checking if chrome is installed

### ISSUE THREAD

**Issue by o6x** [Rdimo/Hazard-Token-Grabber-V2#65]
Traceback (most recent call last):
  File "main.py", line 320, in <module>
  File "main.py", line 37, in init
  File "main.py", line 115, in grabPassword
  File "main.py", line 88, in get_master_key
FileNotFoundError: [Errno 2] No such file or directory: 'C:\Users\user\AppData\Local\Google\Chrome\User Data\Local State'

Getting this error when I exec the compiled version

**Comment by Rdimo** [comment]
it should check if google is installed or not, so just download the newer version
